package com.forkexec.pts.ws.frontend;

import static javax.xml.ws.BindingProvider.ENDPOINT_ADDRESS_PROPERTY;

import java.util.Map;

import javax.xml.ws.BindingProvider;

import com.forkexec.pts.ws.BadInitFault_Exception;
import com.forkexec.pts.ws.EmailAlreadyExistsFault_Exception;
import com.forkexec.pts.ws.InvalidEmailFault_Exception;
import com.forkexec.pts.ws.InvalidPointsFault_Exception;
import com.forkexec.pts.ws.NotEnoughBalanceFault_Exception;
import com.forkexec.pts.ws.PointsPortType;
import com.forkexec.pts.ws.PointsService;
import com.forkexec.pts.ws.cli.PointsClient;

import pt.ulisboa.tecnico.sdis.ws.uddi.UDDINaming;

/**
 * FrontEnd port wrapper.
 *
 * Adds easier end point address configuration to the Port generated by
 * wsimport.
 */
public class PointsFrontEnd {

	/** WS service */
	PointsService service = null;

	/** WS port (port type is the interface, port is the implementation) */
	PointsPortType port = null;

	/** UDDI server URL */
	private String uddiURL = null;

	/** WS name */
	private String wsName = null;

	/** WS end point address */
	private String wsURL = null; // default value is defined inside WSDL

	public String getWsURL() {
		return wsURL;
	}

	/** output option **/
	private boolean verbose = false;

	public boolean isVerbose() {
		return verbose;
	}

	public void setVerbose(boolean verbose) {
		this.verbose = verbose;
	}

	/** constructor with provided UDDI location and name */
	public PointsFrontEnd(String uddiURL, String wsName) throws PointsFrontEndException {
		this.uddiURL = uddiURL;
		this.wsName = wsName;
	}

	/** UDDI lookup */
	private void uddiLookup() throws PointsFrontEndException {
		try {
			if (verbose)
				System.out.printf("Contacting UDDI at %s%n", uddiURL);
			UDDINaming uddiNaming = new UDDINaming(uddiURL);

			if (verbose)
				System.out.printf("Looking for '%s'%n", wsName);
			wsURL = uddiNaming.lookup(wsName);

		} catch (Exception e) {
			String msg = String.format("FrontEnd failed lookup on UDDI at %s!", uddiURL);
			throw new PointsFrontEndException(msg, e);
		}

		if (wsURL == null) {
			String msg = String.format("Service with name %s not found on UDDI at %s", wsName, uddiURL);
			throw new PointsFrontEndException(msg);
		}
	}

	/** Stub creation and configuration */
	private void createStub() {
		if (verbose)
			System.out.println("Creating stub ...");
		service = new PointsService();
		port = service.getPointsPort();

		if (wsURL != null) {
			if (verbose)
				System.out.println("Setting endpoint address ...");
			BindingProvider bindingProvider = (BindingProvider) port;
			Map<String, Object> requestContext = bindingProvider.getRequestContext();
			requestContext.put(ENDPOINT_ADDRESS_PROPERTY, wsURL);
		}
	}

	// remote invocation methods ----------------------------------------------

	public void activateUser(String userEmail) throws EmailAlreadyExistsFault_Exception, InvalidEmailFault_Exception {
    PointsClient cli = null;
    try {
      cli = new PointsClient(uddiURL, wsName);
    } catch (Exception e) {
      // FIXME - IGNORE
    }
    cli.activateUser(userEmail);
	}

	public int pointsBalance(String userEmail) throws InvalidEmailFault_Exception {
    PointsClient cli = null;
    try {
      cli = new PointsClient(uddiURL, wsName);
    } catch (Exception e) {
      // FIXME - IGNORE
    }
		return cli.pointsBalance(userEmail);
	}

	public int addPoints(String userEmail, int pointsToAdd)
			throws InvalidEmailFault_Exception, InvalidPointsFault_Exception {
    PointsClient cli = null;
    try {
      cli = new PointsClient(uddiURL, wsName);
    } catch (Exception e) {
      // FIXME - IGNORE
    }
		return cli.addPoints(userEmail, pointsToAdd);
	}

	public int spendPoints(String userEmail, int pointsToSpend)
			throws InvalidEmailFault_Exception, InvalidPointsFault_Exception, NotEnoughBalanceFault_Exception {
    PointsClient cli = null;
    try {
      cli = new PointsClient(uddiURL, wsName);
    } catch (Exception e) {
      // FIXME - IGNORE
    }
		return cli.spendPoints(userEmail, pointsToSpend);
	}

	// control operations -----------------------------------------------------

	public String ctrlPing(String inputMessage) {
    PointsClient cli = null;
    try {
      cli = new PointsClient(uddiURL, wsName);
    } catch (Exception e) {
      // FIXME - IGNORE
    }
		return cli.ctrlPing(inputMessage);
	}

	public void ctrlClear() {
    PointsClient cli = null;
    try {
      cli = new PointsClient(uddiURL, wsName);
    } catch (Exception e) {
      // FIXME - IGNORE
    }
		cli.ctrlClear();
	}

	public void ctrlInit(int startPoints) throws BadInitFault_Exception {
    PointsClient cli = null;
    try {
      cli = new PointsClient(uddiURL, wsName);
    } catch (Exception e) {
      // FIXME - IGNORE
    }
    cli.ctrlInit(startPoints);
	}

}
